aditional fields for entities
StudentLgotnik/SEP pull request #3
Opened 2019-11-17 15:51 UTC by StudentLgotnik

2019-11-17 17:20 UTC, spanasiuk requested changes

2019-11-17 17:20 UTC, spanasiuk commented on src/main/java/student/enterprise/project/dto/enums/RepeatFrequency.java
> +public enum RepeatFrequency {
Лучше дать возможность выбирать конкретные дни недели из первой и второй недель, например: каждый понедельник и четверг первой недели, а так же вторник и пятницу второй

2019-11-17 17:20 UTC, spanasiuk commented on src/main/java/student/enterprise/project/entity/ChangeEntity.java
>  @Table(name = "changes")
Имя таблицы надо будет только для полноценных энтити

2019-11-17 17:20 UTC, spanasiuk commented on src/main/java/student/enterprise/project/entity/GroupEntity.java
> +  @Column(name = "created", columnDefinition = "DATE")
почему не timestamp?

2019-11-17 17:20 UTC, spanasiuk commented on src/main/java/student/enterprise/project/entity/LecturerEntity.java
> +    private LecturerDegree degree;
Если этого нет в rozklad api, то лучше убрать

2019-11-17 17:20 UTC, spanasiuk commented on src/main/java/student/enterprise/project/entity/RepeatableChangeEntity.java
> +    private RepeatFrequency frequency;
опять же, описал в Enum

2019-11-17 17:20 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/entity/UserEntity.java
> +  private String email;
он нам не нужон

2019-11-17 17:20 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/entity/UserPassword.java
> +    private String salt;
зачем соль?

2019-11-17 17:20 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/service/FileService.java
> +    File getFile(Path path);
тут стримы лучше

2019-11-17 17:20 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/service/impl/GroupService.java
> +package student.enterprise.project.service.impl;
не надо под каждый сервис интерфейсы и имплементации

2019-11-17 17:20 UTC, iSan4eZ commented on src/test/java/student/enterprise/project/service/GroupServiceTest.java
> +import student.enterprise.project.service.impl.GroupService;
не надо под каждый сервис интерфейсы и имплементации

2019-11-19 14:32 UTC, spanasiuk requested changes

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/config/SepConfig.java
> +    public ModelMapper modelMapper() {
@Bean
  public ModelMapper modelMapper() {
    ModelMapper modelMapper = new ModelMapper();
    modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
    return modelMapper;
  }

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/dto/ChangeDTO.java
> +    private LecturerEntity lecturerEntity;
Не энтити, а DTO

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/dto/GroupDTO.java
> +    private List<ChangeEntity> changeList;
тоже ДТО

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/dto/LecturerDTO.java
> +    private List<ChangeEntity> lessonList;
ДТО

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/dto/SubjectDTO.java
> +    private List<ChangeEntity> userRoleList;
ДТО

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/dto/UserDTO.java
> +    private List<UserGroupEntity> groupRoleList;
дто

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/service/ChangeService.java
> +    List<ChangeDTO> toDto(ChangeEntity entity);
для этого конвертеры надо делать. Заведи на меня тикет

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/service/impl/ChangeServiceImpl.java
> +    public List<ChangeDTO> toDto(ChangeEntity entity) {
на меня тикет с конвертером

2019-11-19 14:32 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/dto/enums/RepeatFrequency.java
> +    EVERY_TWO_WEEKS(14);
все равно не выставить никак кастомные варианты. Мне кажется, энам тут не подойдёт

2019-11-22 15:08 UTC, spanasiuk approved these changes

2019-11-22 20:23 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/entity/UserPassword.java
> +    private String salt;
Не следует использовать Id в качестве соли, так как соль должна подходить под следующие критерии: 
1) должна быть случайной, и не зависеть от других параметров
2) иметь статическую длину(желательно больще 10 символов)
3) состоять из всех доступных символов

2019-11-22 20:39 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/dto/enums/RepeatFrequency.java
> +public enum RepeatFrequency {
Удалил этот энам

2019-11-22 20:40 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/entity/ChangeEntity.java
>  @Table(name = "changes")
Удалил анотации, оставил только @Data

2019-11-22 20:40 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/entity/GroupEntity.java
> +  @Column(name = "created", columnDefinition = "DATE")
Исправил

2019-11-22 20:45 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/entity/LecturerEntity.java
> +    private LecturerDegree degree;
Оно есть, правда нужно вытащить со строки

2019-11-22 20:45 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/entity/RepeatableChangeEntity.java
> +    private RepeatFrequency frequency;
Убрал этот параметр

2019-11-22 20:46 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/entity/UserEntity.java
> +  private String email;
Убрал

2019-11-22 20:46 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/service/FileService.java
> +    File getFile(Path path);
Переписал под стримы

2019-11-22 20:46 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/service/impl/GroupService.java
> +package student.enterprise.project.service.impl;
Я бы предпочел операться на абстракцию, чем на имплементацию

2019-11-22 20:52 UTC, StudentLgotnik commented on src/test/java/student/enterprise/project/service/GroupServiceTest.java
> +import student.enterprise.project.service.impl.GroupService;
Создав интерфейс под каждый сервис, можна будет убедиться, что методы с параметрами читабельны, и сразу понятно что они делают даже не видя имплементации, приватные методы не будут маячить перед глазами

2019-11-22 20:53 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/dto/ChangeDTO.java
> +    private LecturerEntity lecturerEntity;
DTO

2019-11-22 20:53 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/dto/LecturerDTO.java
> +    private List<ChangeEntity> lessonList;
DTO

2019-11-22 20:53 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/dto/SubjectDTO.java
> +    private List<ChangeEntity> userRoleList;
DTO

2019-11-22 20:53 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/dto/UserDTO.java
> +    private List<UserGroupEntity> groupRoleList;
DTO

2019-11-22 20:54 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/service/ChangeService.java
> +    List<ChangeDTO> toDto(ChangeEntity entity);
Завел

2019-11-22 20:54 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/service/impl/ChangeServiceImpl.java
> +    public List<ChangeDTO> toDto(ChangeEntity entity) {
Завел

2019-11-22 20:55 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/dto/enums/RepeatFrequency.java
> +    EVERY_TWO_WEEKS(14);
Этого уже нет

2019-11-22 20:56 UTC, StudentLgotnik commented on src/main/java/student/enterprise/project/dto/GroupDTO.java
> +    private List<ChangeEntity> changeList;
ДТО

2019-11-23 11:55 UTC, spanasiuk requested changes

2019-11-23 11:55 UTC, iSan4eZ commented on src/main/java/student/enterprise/project/entity/RepeatableChangeEntity.java
> +    private Short repeatDate;
добавь коммент, описывающий логику этого поля и, желательно, назвать его как-то иначе

2019-11-24 10:18 UTC, spanasiuk approved these changes

2019-11-24 10:22 UTC, merged